[project]
authors = ["mragsac <mragsac@ucsd.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "bnfo262-2026-teaching"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = ">=4.5.1,<5"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
